name: data601
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - packaging
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch>=2.5.1
      - torchvision
      - torchaudio
      - transformers>=4.48.0
      - accelerate>=1.2.0
      - bitsandbytes>=0.45.0
      - peft
      - trl
      - datasets
      - wandb
      - pandas
      - scikit-learn
      - matplotlib
      - sentencepiece
      - tqdm